### ISSUE TITLE
Auto Focus Encounters

### ISSUE THREAD

**Issue by Xilous** [SugarF0x/simple-assistant#11]
Not sure if anyone else is experiencing this issue;

Extension no longer able to focus properly on the travel page.
Step button still works~
Button to open the gather / attack NPC page no longer focuses from the travel page.

But once within the gather or attack NPC page, action button still focuses properly.

**Comment by SugarF0x** [comment]
@Xilous thanks for the report! I don't play much so these issue tickets are the best thing to let me know something doesn't work as it used to
I'l see to have it fixed this week

**Comment by SugarF0x** [comment]
Should be fixed in the next update once the update gets verified on chrome store 👐 

Thanks again for the report!
