### ISSUE TITLE
Does not work any more :(

### ISSUE THREAD

**Issue by F1L1Ndno** [SugarF0x/simple-assistant#17]
With the game update on May 13, when I access the game's web page with extension enabled, only a gray window appears on the screen
![image](https://github.com/SugarF0x/simple-assistant/assets/13280276/4a9a4e2d-7278-4122-8c45-de191167baaa)

**Comment by SugarF0x** [comment]
thanks for the report
just added a hotfix for it in 3.9.4 and uploaded to chrome store
shall be auto updated once goes through with the verification
